INSERT INTO article(id, title, content) VALUES(1, '가가가가', '1111')
INSERT INTO article(id, title, content) VALUES(2, '나나나나', '2222')
INSERT INTO article(id, title, content) VALUES(3, '다다다다', '3333')
INSERT INTO article(id, title, content) VALUES(4, '라라라라', '4444')
INSERT INTO article(id, title, content) VALUES(5, '마마마마', '5555')
INSERT INTO article(id, title, content) VALUES(6, '바바바바', '6666')

INSERT INTO comment(id, article_id, nickname, body) VALUES(1, 4, '게시글', '5555')
INSERT INTO comment(id, article_id, nickname, body) VALUES(2, 5, '게시글', '5555')
INSERT INTO comment(id, article_id, nickname, body) VALUES(3, 6, '게시글', '6666')
